name: Azure Steps

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP_NAME: ShadowPivot
  WEBAPP_NAME: shadow-pivot-nextjsv3

jobs:
  azure-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB5556BB61184D708CE635E139634BA5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_175C227A37A54C389C8137801ABCE231 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD05A5B616EC413AA247DA3C419676F7 }}

      - name: Restart Azure Web App to trigger GHCR image pull
        run: |
          az webapp restart \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP_NAME