name: Main Workflow

on:
  workflow_dispatch:

jobs:
  trigger-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build and Push Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-and-push.yml',
              ref: context.ref,
            });

  trigger-azure-steps:
    runs-on: ubuntu-latest
    needs: trigger-build-and-push
    steps:
      - name: Trigger Azure Steps Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'azure-steps.yml',
              ref: context.ref,
            });